olenaza_blog_pages:
    resource: "@OlenazaBlogBundle/Resources/config/routing.yml"

olenaza_blog_posts:
    resource: "@OlenazaBlogBundle/Resources/config/routing_posts.yml"
    prefix:   /posts

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
