<?php

namespace Olenaza\BlogBundle\Repository;

/**
 * AboutPageRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AboutPageRepository extends \Doctrine\ORM\EntityRepository
{
}
