welcome:
    path:     /
    defaults: { _controller: OlenazaBlogBundle:Welcome:index }

about:
    path:     /about
    defaults: { _controller: OlenazaBlogBundle:About:index }

comment_update:
    path:     /comments/{id}/update
    defaults: { _controller: OlenazaBlogBundle:Comment:edit}
    requirements:
        id: '\d+'
