posts_list:
    path:     /{page}
    defaults: { _controller: OlenazaBlogBundle:Post:list, page: 1 }
    methods: [GET]
    requirements:
      page: '\d+'

posts_list_by_publication_date:
    path:     /by-publication-date/{page}
    defaults: { _controller: OlenazaBlogBundle:Post:listByPublicationDate, page: 1 }
    methods: [GET]
    requirements:
      page: '\d+'

posts_list_by_category:
    path:     /category/{categoryId}
    defaults: { _controller: OlenazaBlogBundle:Category:showPosts }
    methods: [GET]

posts_list_no_page:
    path:     /
    defaults:
      _controller: FrameworkBundle:Redirect:urlRedirect
      path: /posts
      permanent: true
    methods: [GET]

post_show:
    path:     /{slug}
    defaults: { _controller: OlenazaBlogBundle:Post:show, slug: 2 }
