posts_list_by_category:
    path:     /category/{slug}/{page}
    defaults: { _controller: OlenazaBlogBundle:Post:listByCategory, page: 1 }
    requirements:
        page: '\d+'

posts_list_by_tag:
    path:     /tag/{name}/{page}
    defaults: { _controller: OlenazaBlogBundle:Post:listByTag, page: 1 }
    requirements:
        page: '\d+'

posts_search:
    path:     /search/{text}
    defaults: { _controller: OlenazaBlogBundle:Post:search }

posts_search_results:
    path:     /search_results/{page}
    defaults: { _controller: OlenazaBlogBundle:Post:showSearchResults, page: 1}
    requirements:
        page: '\d+'

posts_list:
    path:     /{page}
    defaults: { _controller: OlenazaBlogBundle:Post:list, page: 1}
    requirements:
        page: '\d+'

post_comment_edit:
    path:     /{slug}/comment/{commentToEditId}/edit
    defaults: { _controller: OlenazaBlogBundle:Post:show}
    requirements:
        commentToEditId: '\d+'

post_comment_delete:
    path:     /{slug}/comment/{commentToDeleteId}/delete
    defaults: { _controller: OlenazaBlogBundle:Post:show}
    requirements:
        commentToDeleteId: '\d+'

post_show:
    path:     /{slug}
    defaults: { _controller: OlenazaBlogBundle:Post:show}
