posts_list_by_category:
    path:     /category/{slug}/{page}
    defaults: { _controller: OlenazaBlogBundle:Post:listByCategory, page: 1 }
    requirements:
        page: '\d+'

posts_list_by_tag:
    path:     /tag/{name}/{page}
    defaults: { _controller: OlenazaBlogBundle:Post:listByTag, page: 1 }
    requirements:
        page: '\d+'

posts_search:
    path:     /search/{page}
    defaults: { _controller: OlenazaBlogBundle:Post:search, page: 1 }
    requirements:
        page: '\d+'

posts_list:
    path:     /{page}
    defaults: { _controller: OlenazaBlogBundle:Post:list, page: 1}
    requirements:
        page: '\d+'

post_like:
    path:     /{slug}/like/{username}
    defaults: { _controller: OlenazaBlogBundle:Like:create}

post_show:
    path:     /{slug}
    defaults: { _controller: OlenazaBlogBundle:Post:show}

remove_trailing_slash:
    path: /{url}
    defaults: { _controller: OlenazaBlogBundle:Redirecting:removeTrailingSlash }
    requirements:
        url: .*/$
    methods: [GET]
