services:
    twig.extension.add_ellipsis:
        class: Olenaza\BlogBundle\Extension\Twig\BlogTwigExtension
        tags:
             - { name: twig.extension }

    admin.post:
        class: Olenaza\BlogBundle\Admin\PostAdmin
        arguments: [~, Olenaza\BlogBundle\Entity\Post, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Content"
              label: "Post"
              show_mosaic_button: false

    admin.tag:
        class: Olenaza\BlogBundle\Admin\TagAdmin
        arguments: [~, Olenaza\BlogBundle\Entity\Tag, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Content"
              label: "Tag"
              show_mosaic_button: false

    admin.category:
        class: Olenaza\BlogBundle\Admin\CategoryAdmin
        arguments: [~, Olenaza\BlogBundle\Entity\Category, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Content"
              label: "Category"
              show_mosaic_button: false

    admin.settings:
        class: Olenaza\BlogBundle\Admin\SettingAdmin
        arguments: [~, Olenaza\BlogBundle\Entity\Setting, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Pages and Settings"
              label: "Page/Setting"
              show_mosaic_button: false

    blog.menu_builder:
        class: Olenaza\BlogBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", "@=service('doctrine').getRepository('OlenazaBlogBundle:Category')"]
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
            - { name: knp_menu.menu_builder, method: createBottomMenu, alias: bottom }

    blog.breadcrumbs_creator:
        class: Olenaza\BlogBundle\Menu\BreadcrumbsCreator
        arguments: ["@white_october_breadcrumbs", "@=service('doctrine').getRepository('OlenazaBlogBundle:Category')"]

    blog.comment_voter:
        class: Olenaza\BlogBundle\Security\CommentVoter
        arguments: ['@security.access.decision_manager']
        tags:
            - { name: security.voter }
        # small performance boost
        public: false

    blog.user_provider:
        class:     Olenaza\BlogBundle\Security\Core\User\MyFOSUBUserProvider
        arguments: ['@fos_user.user_manager', { facebook: facebookId }]
