services:
    twig.extension.add_ellipsis:
        class: Olenaza\BlogBundle\Extension\Twig\BlogTwigExtension
        tags:
               - { name: twig.extension }

    blog.slugger:
        class: Olenaza\BlogBundle\Utils\Slugger
